### ISSUE TITLE
Consider publishing a new version of `btfdump` on `crates.io`

### ISSUE THREAD

**Issue by Officeyutong** [anakryiko/btfdump#5]
https://github.com/anakryiko/btfdump/issues/3 is fixed, but the changes haven't been published to `crates.io`. 

Crates.io requires that any packages uploaded have to specify packages by version, not by git repo and rev. Since the changes of https://github.com/anakryiko/btfdump/pull/4 haven't been published to crates.io, any crates that dependends on `btfdump = "0.0.1"` will still suffer from the bug.

**Comment by anakryiko** [comment]
Pushed v0.0.2 to crates.io.
