### ISSUE TITLE
Release with updated dependencies

### ISSUE THREAD

**Issue by ajwerner** [anakryiko/btfdump#8]
When I use the "0.0.2" version, I see the stale `Cargo.toml` and get an ancient `object` crate version. It seems like the `0.0.2` tag is missing on github. Any chance you can either cut another release or verify that crates.io sees the newer dependencies. 

See https://crates.io/crates/btfdump/0.0.2/dependencies.

**Comment by anakryiko** [comment]
Pushed v0.0.2 tag (retroactively). Also cut v0.0.3 with updated Cargo.toml (as of May, so might be a bit outdated already), but also support for ENUM64 BTF kinds. Release: https://github.com/anakryiko/btfdump/releases/tag/v0.0.3, crates.io: https://crates.io/crates/btfdump/0.0.3

If some of the dependencies are still too old, please feel free to send PR my way, I'll land it no problem. Thanks!

**Comment by ajwerner** [comment]
Thank you!
